server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8086

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-07987265.okta.com/oauth2/default
      client:
        registration:
          my-internal-client: #here any name you can give
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            client-id: 0oaeqpp1tbCFy7iRu5d7
            client-secret: nXS36XXM498eaTz8Zc7J5BRiS8PWwBr4TJWFUAzG5VyC4vGZbkX4Yh9fno6GQZa6
        provider:
          okta:
            issuerUri: https://dev-07987265.okta.com/oauth2/default


#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8084/eureka/

management:
  health:
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health


  endpoint:
    health:
      show-details: ALWAYS


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-07987265.okta.com/oauth2/default
    audience: api://default
